### ISSUE TITLE
建议将树结构改为单层显示

### ISSUE THREAD

**Issue by allblue** [aoyiduo/woterm#13]
建议树结构能同时展开多个目录，便于切换

**Comment by getwingm** [comment]
当前是已经提供了两种列表模式的，一种是树形结构，一种单层的列表结构。在【会话列表】和【会话管理】的界面上，左上角有一个按钮，可以很方便在树形结构和列表结构之间切换的。在【会话管理】鼠标右键菜单中，也有列表或树状展示的菜单入口

**Comment by allblue** [comment]
这条是我没发现
