### ISSUE TITLE
建议增加pagent和ssh-agent支持

### ISSUE THREAD

**Issue by allblue** [aoyiduo/woterm#14]
不需要导入私钥，可通过agent自动获取

**Comment by getwingm** [comment]
不是很理解你的意思。如果是指跳板机配置的话，那本软是已经支持了的。而且是支持无限层的跳板机。结构就【本地主机】->【跳板机1ProxyJump】->【跳板机2ProxyJump】->【跳板机3ProxyJump】->【跳板机4ProxyJump】->【目标服务器】

**Comment by allblue** [comment]
不是跳转机，而是把密钥用pagent或ssh-agent集中管理，不导入到woterm里，woterm通过pagent或ssh-agent给的接口访问密钥，可以参考下moba、xshell、putty里相关功能实现

**Comment by huichen2018** [comment]
![111](https://user-images.githubusercontent.com/45547620/212840021-0cae0e1d-0fc8-4da0-8410-e5e8e84ee6f9.png)
应该是putty这个功能吧？

**Comment by allblue** [comment]
![image](https://user-images.githubusercontent.com/844763/212844346-9d4bbe1d-dc08-4180-90bf-369bcce08802.png)
不是，这是保存公钥的，pagnet/ssh-agent是私钥

**Comment by getwingm** [comment]
问题已经解决
