### ISSUE TITLE
mac上字体模糊

### ISSUE THREAD

**Issue by Ice-001** [aoyiduo/woterm#16]
macOS Ventura 版本13.0.1

<img width="893" alt="woterm" src="https://user-images.githubusercontent.com/87889710/207520361-d168a81b-ae8f-483c-8914-4d03e4cea924.png">

**Comment by getwingm** [comment]
这种现象是Qt内部BUG来的，不确定是否有合适的方案解决，后续有时间可以试试升级至Qt6看看。
