### ISSUE TITLE
请支持ed25519

### ISSUE THREAD

**Issue by hongnod** [aoyiduo/woterm#2]

**Comment by hongnod** [comment]
指的是证书导入模块，导入时提示
![image](https://user-images.githubusercontent.com/6680267/201590335-095e5328-7546-42b2-b31f-d741ae395427.png)
但实际就是私匙
![image](https://user-images.githubusercontent.com/6680267/201590468-3c6b237d-320e-4fff-928b-65ee150433da.png)

**Comment by getwingm** [comment]
好的，已经加入开发计划，预计接下来的两个版本会实现。

**Comment by hongnod** [comment]
[v9.26.3](https://github.com/aoyiduo/woterm/releases/tag/v9.26.3)  还是不行。

**Comment by hookybaby** [comment]
v9.26.6,也不行
