### ISSUE TITLE
显示的非常奇怪

### ISSUE THREAD

**Issue by donmen5200** [aoyiduo/woterm#20]
不知道为啥在我的mac上显示字体有问题,换了其他的字体也不行,升级了版本也不行
![image](https://user-images.githubusercontent.com/76697072/218312744-8b7e9b33-9e62-47d4-815a-49ef7534b689.png)

**Comment by getwingm** [comment]
只能使用MONO的等宽字体,非等宽字体当前是不支持了.你试一下使用APP推荐的字体或者是系统终端自带的字体.
