### ISSUE TITLE
win10分屏桌面中输入的字符完全不显示

### ISSUE THREAD

**Issue by lnxyz** [aoyiduo/woterm#22]
版本：v9.26.3
os: win 10
主屏2k, 外接 1080p 显示 ，软件在主屏上面 完全正常没有，副屏 输入的字符完全不显示；如下图：

主屏正常显示：
![在主屏正常_1](https://user-images.githubusercontent.com/31302394/223377905-2bed93e4-2a15-45d7-9828-c43cf0342c34.png)
---
副屏异常图：
![副屏异常_1](https://user-images.githubusercontent.com/31302394/223377895-6598ac16-8807-48eb-a10c-ed8c10b8ae8f.png)

**Comment by getwingm** [comment]
更换字体有效果吗?

**Comment by getwingm** [comment]
更换其它字体也是同样效果吗?

**Comment by lnxyz** [comment]
我现在改用linux了，用 9.28.5 没有这个问题了，不用windows好久了。不知道windows上面是否常用这个问题。
