### ISSUE TITLE
建议：减少打开主机的步骤

### ISSUE THREAD

**Issue by islercn** [aoyiduo/woterm#25]
建议在“文件-打开”菜单下面，直接列出来所有保存的主机

同时在打开的会话列表那里点右键，菜单里增加一个打开，下面同样列出来所有保存的主机

**Comment by getwingm** [comment]
在v9.26.5版本开始,已经支持了一个访问历史的快捷按钮,可以快捷直达最近常访问的会话,你体验一下这种实现方式,是否能满足你要求.
