### ISSUE TITLE
新功能请求：主题更换

### ISSUE THREAD

**Issue by duokebei** [aoyiduo/woterm#26]
作者您好，刚刚使用了下，挺符合胃口，但是这个蓝色的主题，看的眼睛比较干涩，想麻烦下作者加入更多主题或者让用户自行对区域进行配色的功能。谢谢。

**Comment by getwingm** [comment]
主题更换及自定义这功能是必定会实现的,但可能要等到今年第三季度才会实现.

**Comment by duokebei** [comment]
> 主题更换及自定义这功能是必定会实现的,但可能要等到今年第三季度才会实现.

还有个选择就是sftp界面可不可以不打开新的一栏，就在当前ssh连接界面的下方或者左方或者右方，sftp能跟随当前cd命令跳转是最好的。

**Comment by duokebei** [comment]
> 这个是已经实现的,在SSH的连接界面上,右键菜单选择SFTP助手.它可以与SSH界面进行目录同步及上传或下载等功能的.

使用SFTP助手并没有达到跟随cd命令进入目标文件夹的效果
![image](https://user-images.githubusercontent.com/75022552/234486635-02992bd6-e10e-4831-9222-449b47d78974.png)

**Comment by getwingm** [comment]
问题已经解决
