### ISSUE TITLE
证书管理

### ISSUE THREAD

**Issue by gsd1508** [aoyiduo/woterm#28]
证书管理根本用不了。你们自己去测试。

**Comment by getwingm** [comment]
你用的是什么系统，是怎样用不了，能把过程描述一下吗？我这边两台服务器一直都是证书的，目前还没有发现问题。我目前用的证书RSA证书。

**Comment by getwingm** [comment]
经测试验证，确实发现自创建的证书均不能正常连接，下一个版本会修复。

**Comment by getwingm** [comment]
经过测试发现有这样奇怪的问题，自创建的证书在测试阿里云和腾讯云服务器，都是可以正常用证书访问的。但在测试全新的自建服务器时，却怎样都连接不上。但密码却是可以连接上的。
这够竟是什么原因，我们再继续查查。

**Comment by getwingm** [comment]
我一共测试了两个服务器，其系统分别是Centos7.0和Centos7.5。7.0是无法使用证书连接上的，而7.5是没有任何问题的。
而7.0的除了WoTerm无法使用证书连接外，使用系统自带的SSH也是无法连接上的。不知道这是7.0的问题还是小于7.0的系统都会存在这个问题？

**Comment by getwingm** [comment]
已经检查了服务端的SSHD的配置，感觉配置是没有问题的，也是支持rsa/ed25519证书的。

**Comment by getwingm** [comment]
问题已经解决
