### ISSUE TITLE
杀毒软件提示安全警告 

### ISSUE THREAD

**Issue by colinshin** [aoyiduo/woterm#31]
symantec杀毒软件提示安全警告

**Comment by colinshin** [comment]
![微信截图_20230629093616](https://github.com/aoyiduo/woterm/assets/64405876/5a4ef374-cabf-45e5-825c-9188f47e4152)

**Comment by getwingm** [comment]
或许是误报，如果是从官方下载的文件，肯定是没有毒的。你可以检查一下文件的签名信息是否被人为窜改了。只要窜改了，那安装时，就会提示软件签名异常的提示的。

**Comment by getwingm** [comment]
你能提取到详细的安全提示内容吗？如果能的话，截图上来看看。
