### ISSUE TITLE
[bug] 多行命令复制粘贴不支持Unix(LF)换行模式

### ISSUE THREAD

**Issue by lnxyz** [aoyiduo/woterm#33]
终端内多行命令复制粘贴后会并成一行，因为没法识别Unix(LF)换行模式，改用 windows换行则可以识别。
版本： 9.28.5

**Comment by getwingm** [comment]
请问你说的终端是指WoTerm吗？复制和粘贴都是在WoTerm内触发吗？能再仔细描述一下这个过程吗？
目前我这边的工程师是没有重现该问题，也有可能是操作过程与你不相同，导致这现象。

**Comment by lnxyz** [comment]
是woterm, 外部复制粘贴及内部复制粘 都 会变成一行。 
os: linuxmint

**Comment by getwingm** [comment]
收到，以后，我们也适配一下这个体统的版本：linuxmint。

**Comment by getwingm** [comment]
你好，我们这边安装了linuxmint21的版本，测试了vim的命令，在vim命令内或外复制或粘贴都是正常，也在localshell本地终端及远程的会话终端中测试都是正常的，没有发现你说的多行粘贴为一行的问题。

能否你仔细的描述你的操作过程，包括全过程所涉及的命令。看看我这边能否重现你的问题。

**Comment by getwingm** [comment]
你好，目前系统还有此问题吗？如果是在vim或vi命令内编辑出现该问题，可以在网上搜索一下:set paste设置粘贴模式和:set nopaste取消粘贴模式，测试验证一下。
