### ISSUE TITLE
Failed to authentication: Access denied for 'password'. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic,password

### ISSUE THREAD

**Issue by shibingli** [aoyiduo/woterm#35]
直接使用命令行没有问题，但是用woterm就会出现在下面的问题。

Failed to authentication: Access denied for 'password'. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic,password

<img width="1180" alt="image" src="https://github.com/aoyiduo/woterm/assets/4089531/60cc43b5-bfd1-4ea9-8073-f39813fd6c85">

**Comment by getwingm** [comment]
那是程序主动输出的错误，方便提示用户登录失败以及失败的原因过程。
如果最终能正常登录的话，那是没有问题的。

所以如果你最终无论怎样都无法登录的话，那可以按以下方式排查一下：
1.命令行下是否启用了证书，如果是的话，你要将证书导入woterm才行。
2.如果都是密码登录的话，那能否方便告知一下目标服务器的ssh-server的版本号以及连接的服务器系统如Centos或Ubuntu等，方便我们排查问题？

**Comment by shibingli** [comment]
密码登陆。

服务器端为： AlmaLinux 9.2
OpenSSH-Server版本为：8.7p1-29.el9_2.x86_64
客户端为： Windows 11 - 22H2（22621.2428）

<img width="435" alt="image" src="https://github.com/aoyiduo/woterm/assets/4089531/fe01c0c8-346b-4534-8021-ad05cdb9e4bf">

<img width="461" alt="image" src="https://github.com/aoyiduo/woterm/assets/4089531/d4ce9907-8636-42c4-94d7-05aef255b7c8">

**Comment by getwingm** [comment]
你好，这个问题，突然也出现在我的环境里，经过排查确认是程序加载时，默认会加载~/.ssh/config 和 /etc/ssh/ssh_config下的配置，因为名字或IP相同的缘故，从而导致某些参数被修改。

这缺陷将在9.29.2的版本修复，将在本周内会发布，请留意最新版本。
此外，如果你急着使用，也可以定位至~/.ssh/config 和 /etc/ssh/ssh_config文件，并进行修改。

**Comment by shibingli** [comment]
3Q
